### ISSUE TITLE
HTML Parser - Parsing semester as course

### ISSUE THREAD

**Issue by sakrifor** [acmauth/GradeParser#1]
There seems to be some problem with a submission where the whole semester grades are handled as one course, raising an exception after a while. I am attaching the exception and the debugger output where it seems that the semester is handled as a course. The submission causing the issue is the one made on the 25/07. 

![Annotation 2019-08-20 163837](https://user-images.githubusercontent.com/8472778/63352018-fe2eb600-c368-11e9-8f1f-2b489487b333.png)
![Annotation 2019-08-20 163844](https://user-images.githubusercontent.com/8472778/63352019-fe2eb600-c368-11e9-9669-52899fd61413.png)

**Comment by din0s** [comment]
Fixed in ecfc7d25bc98630aa64608e138427741909b43d3.
