### ISSUE TITLE
PDF Parser - Missing Grades 

### ISSUE THREAD

**Issue by sakrifor** [acmauth/GradeParser#3]
Missing grades seems to cause a problem to the pdf parser since the regex used can't handle them. If a grade is missing the code of the next course is used as the grade causing missing courses from the final csv. Submission tested 28/07 5:55AM
![Annotation 2019-08-20 172655](https://user-images.githubusercontent.com/8472778/63356148-f292bd80-c36f-11e9-8239-d835ef25dfa6.png)

**Comment by din0s** [comment]
Fixed in 6df340e3a89f49e86bf72cdcbb328da25bcb4c23 with some Regex magic. Thanks (:
